### ISSUE TITLE
Pixel ratio for buffer resolution

### ISSUE THREAD

**Issue by marioecg** [patriciogonzalezvivo/glsl-sandbox#4]
Should we take into account the pixel ratio when setting or updating the size of the buffers? If you do any operations inside a shader that require the resolution you might get different results according to the device pixel ratio.

For instance, I have a pixel ratio of 2 and in the example shader my scene is divided, I believe because of the use of `fract`:

<img width="1512" alt="Screen Shot 2023-08-14 at 11 03 50" src="https://github.com/patriciogonzalezvivo/glsl-sandbox/assets/13428979/5eb02cca-434b-4d7b-857d-9fb340119918">

**Comment by patriciogonzalezvivo** [comment]
Good point! Yes, the resolution variable should be scale according to the pixel density on the setSize function. Do you mind making a PR?

**Comment by marioecg** [comment]
Will work on it.

**Comment by marioecg** [comment]
I noticed that when you resize the window for a while the canvas starts to get a bit jittery and slow, specially for the ping-pong buffers. Do you know why?

I'm testing on a 14" M1 Macbook Pro

<img width="894" alt="Screen Shot 2023-08-14 at 15 20 33" src="https://github.com/patriciogonzalezvivo/glsl-sandbox/assets/13428979/ed1360d3-2cdb-49bc-940e-b58f110aea66">
