### ISSUE TITLE
feedback effect gets slow when resizing window

### ISSUE THREAD

**Issue by marioecg** [patriciogonzalezvivo/glsl-sandbox#7]
I noticed that when you resize the window for a while the canvas starts to get a bit jittery and slow, specially for the ping-pong buffers. Do you know why?

I'm testing on a 14" M1 Macbook Pro

<img width="894" alt="Screen Shot 2023-08-14 at 15 20 33" src="https://github.com/patriciogonzalezvivo/glsl-sandbox/assets/13428979/13fa0d03-3210-4e2e-8959-f45455facdfa">

**Comment by marioecg** [comment]
It seems to affect all of what's rendered, not just the ping-pong outputs.

**Comment by patriciogonzalezvivo** [comment]
My bad, I was re-triggering `draw()` in the example and doubling the amount of draw calls every time.
https://github.com/patriciogonzalezvivo/glsl-sandbox/commit/5d26de82f360bcf0de789fbb55a654e380aee127
